### ISSUE TITLE
Exception: java.io.IOException - /theme.res not found

### ISSUE THREAD

**Issue by balakrishna501** [sergeyCodenameOne/UberEatsClone#12]
SourceChangeWatcher running.  Watching directories [D:\UberEatsClone-master\common\src\main\java]
[EDT] 0:0:0,17 - Codename One revisions: 7dd4e7d08b3442d90959477ee52a5ae8c4361b29

[EDT] 0:0:0,17 - Exception: java.io.IOException - /theme.res not found
java.io.IOException: /theme.res not found
	at com.codename1.ui.util.Resources.open(Resources.java:756)
	at com.codename1.ui.util.Resources.openLayered(Resources.java:720)
	at com.codename1.ui.util.Resources.openLayered(Resources.java:684)
	at com.codename1.demos.grub.Grub.init(Grub.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.codename1.impl.javase.Executor$4$1.run(Executor.java:308)
	at com.codename1.ui.Display.processSerialCalls(Display.java:1368)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:1155)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
java.lang.NullPointerException
	at com.codename1.demos.grub.views.AccountView.<init>(AccountView.java:89)
	at com.codename1.demos.grub.controllers.AccountController.<init>(AccountController.java:49)
	at com.codename1.demos.grub.Grub.actionPerformed(Grub.java:90)
	at com.codename1.demos.grub.Grub.actionPerformed(Grub.java:48)
	at com.codename1.ui.util.EventDispatcher.fireActionEvent(EventDispatcher.java:349)
	at com.codename1.rad.controllers.Controller.dispatchEvent(Controller.java:159)
	at com.codename1.demos.grub.Grub.start(Grub.java:287)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.codename1.impl.javase.Executor$4$1.run(Executor.java:314)
	at com.codename1.ui.Display.processSerialCalls(Display.java:1368)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:1155)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)

**Comment by balakrishna501** [comment]
i have just checkout code and run mvn install

im getting above error,plz help on this..i have wasted 2 days on this error

**Comment by danielsxavier** [comment]
Same issue here. I tried on linux and windows.

**Comment by shai-almog** [comment]
Make sure you're using JDK 11 to compile the project. 
Alternatively you can use a newer JDK but would need to update the maven pom to the latest version.

**Comment by danielsxavier** [comment]
Thanks @shai-almog ! I changed to jdk 11 and works like a charm.
